/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// AuthAnonLoginRequest struct for AuthAnonLoginRequest
type AuthAnonLoginRequest struct {
	// Whether to create a user, if it does not exist
	CreateUser *bool `json:"create_user,omitempty"`
	// User's login ID
	Username string `json:"username"`
}

// NewAuthAnonLoginRequest instantiates a new AuthAnonLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthAnonLoginRequest(username string) *AuthAnonLoginRequest {
	this := AuthAnonLoginRequest{}
	this.Username = username
	return &this
}

// NewAuthAnonLoginRequestWithDefaults instantiates a new AuthAnonLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthAnonLoginRequestWithDefaults() *AuthAnonLoginRequest {
	this := AuthAnonLoginRequest{}
	return &this
}

// GetCreateUser returns the CreateUser field value if set, zero value otherwise.
func (o *AuthAnonLoginRequest) GetCreateUser() bool {
	if o == nil || isNil(o.CreateUser) {
		var ret bool
		return ret
	}
	return *o.CreateUser
}

// GetCreateUserOk returns a tuple with the CreateUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthAnonLoginRequest) GetCreateUserOk() (*bool, bool) {
	if o == nil || isNil(o.CreateUser) {
		return nil, false
	}
	return o.CreateUser, true
}

// HasCreateUser returns a boolean if a field has been set.
func (o *AuthAnonLoginRequest) HasCreateUser() bool {
	if o != nil && !isNil(o.CreateUser) {
		return true
	}

	return false
}

// SetCreateUser gets a reference to the given bool and assigns it to the CreateUser field.
func (o *AuthAnonLoginRequest) SetCreateUser(v bool) {
	o.CreateUser = &v
}

// GetUsername returns the Username field value
func (o *AuthAnonLoginRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *AuthAnonLoginRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *AuthAnonLoginRequest) SetUsername(v string) {
	o.Username = v
}

func (o AuthAnonLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CreateUser) {
		toSerialize["create_user"] = o.CreateUser
	}
	if true {
		toSerialize["username"] = o.Username
	}
	return json.Marshal(toSerialize)
}

type NullableAuthAnonLoginRequest struct {
	value *AuthAnonLoginRequest
	isSet bool
}

func (v NullableAuthAnonLoginRequest) Get() *AuthAnonLoginRequest {
	return v.value
}

func (v *NullableAuthAnonLoginRequest) Set(val *AuthAnonLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthAnonLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthAnonLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthAnonLoginRequest(val *AuthAnonLoginRequest) *NullableAuthAnonLoginRequest {
	return &NullableAuthAnonLoginRequest{value: val, isSet: true}
}

func (v NullableAuthAnonLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthAnonLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
