/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// StorageGetCounterResponse struct for StorageGetCounterResponse
type StorageGetCounterResponse struct {
	// Value of the counter
	Count int32 `json:"count"`
}

// NewStorageGetCounterResponse instantiates a new StorageGetCounterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageGetCounterResponse(count int32) *StorageGetCounterResponse {
	this := StorageGetCounterResponse{}
	this.Count = count
	return &this
}

// NewStorageGetCounterResponseWithDefaults instantiates a new StorageGetCounterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageGetCounterResponseWithDefaults() *StorageGetCounterResponse {
	this := StorageGetCounterResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *StorageGetCounterResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *StorageGetCounterResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *StorageGetCounterResponse) SetCount(v int32) {
	o.Count = v
}

func (o StorageGetCounterResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableStorageGetCounterResponse struct {
	value *StorageGetCounterResponse
	isSet bool
}

func (v NullableStorageGetCounterResponse) Get() *StorageGetCounterResponse {
	return v.value
}

func (v *NullableStorageGetCounterResponse) Set(val *StorageGetCounterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageGetCounterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageGetCounterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageGetCounterResponse(val *StorageGetCounterResponse) *NullableStorageGetCounterResponse {
	return &NullableStorageGetCounterResponse{value: val, isSet: true}
}

func (v NullableStorageGetCounterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageGetCounterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
