/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// StorageGetBlobResponse struct for StorageGetBlobResponse
type StorageGetBlobResponse struct {
	// CAS value used for future operations
	Cas *string `json:"cas,omitempty"`
	// Blob value
	Value *string `json:"value,omitempty"`
}

// NewStorageGetBlobResponse instantiates a new StorageGetBlobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageGetBlobResponse() *StorageGetBlobResponse {
	this := StorageGetBlobResponse{}
	return &this
}

// NewStorageGetBlobResponseWithDefaults instantiates a new StorageGetBlobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageGetBlobResponseWithDefaults() *StorageGetBlobResponse {
	this := StorageGetBlobResponse{}
	return &this
}

// GetCas returns the Cas field value if set, zero value otherwise.
func (o *StorageGetBlobResponse) GetCas() string {
	if o == nil || isNil(o.Cas) {
		var ret string
		return ret
	}
	return *o.Cas
}

// GetCasOk returns a tuple with the Cas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageGetBlobResponse) GetCasOk() (*string, bool) {
	if o == nil || isNil(o.Cas) {
		return nil, false
	}
	return o.Cas, true
}

// HasCas returns a boolean if a field has been set.
func (o *StorageGetBlobResponse) HasCas() bool {
	if o != nil && !isNil(o.Cas) {
		return true
	}

	return false
}

// SetCas gets a reference to the given string and assigns it to the Cas field.
func (o *StorageGetBlobResponse) SetCas(v string) {
	o.Cas = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *StorageGetBlobResponse) GetValue() string {
	if o == nil || isNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageGetBlobResponse) GetValueOk() (*string, bool) {
	if o == nil || isNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *StorageGetBlobResponse) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *StorageGetBlobResponse) SetValue(v string) {
	o.Value = &v
}

func (o StorageGetBlobResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Cas) {
		toSerialize["cas"] = o.Cas
	}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableStorageGetBlobResponse struct {
	value *StorageGetBlobResponse
	isSet bool
}

func (v NullableStorageGetBlobResponse) Get() *StorageGetBlobResponse {
	return v.value
}

func (v *NullableStorageGetBlobResponse) Set(val *StorageGetBlobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageGetBlobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageGetBlobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageGetBlobResponse(val *StorageGetBlobResponse) *NullableStorageGetBlobResponse {
	return &NullableStorageGetBlobResponse{value: val, isSet: true}
}

func (v NullableStorageGetBlobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageGetBlobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
