/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// LeaderboardsSetScoreResponse struct for LeaderboardsSetScoreResponse
type LeaderboardsSetScoreResponse struct {
	// Latest score to be returned
	Score *float64          `json:"score,omitempty"`
	Tier  *LeaderboardsTier `json:"tier,omitempty"`
}

// NewLeaderboardsSetScoreResponse instantiates a new LeaderboardsSetScoreResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeaderboardsSetScoreResponse() *LeaderboardsSetScoreResponse {
	this := LeaderboardsSetScoreResponse{}
	return &this
}

// NewLeaderboardsSetScoreResponseWithDefaults instantiates a new LeaderboardsSetScoreResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaderboardsSetScoreResponseWithDefaults() *LeaderboardsSetScoreResponse {
	this := LeaderboardsSetScoreResponse{}
	return &this
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *LeaderboardsSetScoreResponse) GetScore() float64 {
	if o == nil || isNil(o.Score) {
		var ret float64
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeaderboardsSetScoreResponse) GetScoreOk() (*float64, bool) {
	if o == nil || isNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *LeaderboardsSetScoreResponse) HasScore() bool {
	if o != nil && !isNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float64 and assigns it to the Score field.
func (o *LeaderboardsSetScoreResponse) SetScore(v float64) {
	o.Score = &v
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *LeaderboardsSetScoreResponse) GetTier() LeaderboardsTier {
	if o == nil || isNil(o.Tier) {
		var ret LeaderboardsTier
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeaderboardsSetScoreResponse) GetTierOk() (*LeaderboardsTier, bool) {
	if o == nil || isNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *LeaderboardsSetScoreResponse) HasTier() bool {
	if o != nil && !isNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given LeaderboardsTier and assigns it to the Tier field.
func (o *LeaderboardsSetScoreResponse) SetTier(v LeaderboardsTier) {
	o.Tier = &v
}

func (o LeaderboardsSetScoreResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !isNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	return json.Marshal(toSerialize)
}

type NullableLeaderboardsSetScoreResponse struct {
	value *LeaderboardsSetScoreResponse
	isSet bool
}

func (v NullableLeaderboardsSetScoreResponse) Get() *LeaderboardsSetScoreResponse {
	return v.value
}

func (v *NullableLeaderboardsSetScoreResponse) Set(val *LeaderboardsSetScoreResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLeaderboardsSetScoreResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLeaderboardsSetScoreResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeaderboardsSetScoreResponse(val *LeaderboardsSetScoreResponse) *NullableLeaderboardsSetScoreResponse {
	return &NullableLeaderboardsSetScoreResponse{value: val, isSet: true}
}

func (v NullableLeaderboardsSetScoreResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeaderboardsSetScoreResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
