/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// UpdateUserVirtualCurrencyRequest struct for UpdateUserVirtualCurrencyRequest
type UpdateUserVirtualCurrencyRequest struct {
	// Amount to grant
	Amount *int32 `json:"amount,omitempty"`
}

// NewUpdateUserVirtualCurrencyRequest instantiates a new UpdateUserVirtualCurrencyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateUserVirtualCurrencyRequest() *UpdateUserVirtualCurrencyRequest {
	this := UpdateUserVirtualCurrencyRequest{}
	return &this
}

// NewUpdateUserVirtualCurrencyRequestWithDefaults instantiates a new UpdateUserVirtualCurrencyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateUserVirtualCurrencyRequestWithDefaults() *UpdateUserVirtualCurrencyRequest {
	this := UpdateUserVirtualCurrencyRequest{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *UpdateUserVirtualCurrencyRequest) GetAmount() int32 {
	if o == nil || isNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateUserVirtualCurrencyRequest) GetAmountOk() (*int32, bool) {
	if o == nil || isNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *UpdateUserVirtualCurrencyRequest) HasAmount() bool {
	if o != nil && !isNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *UpdateUserVirtualCurrencyRequest) SetAmount(v int32) {
	o.Amount = &v
}

func (o UpdateUserVirtualCurrencyRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateUserVirtualCurrencyRequest struct {
	value *UpdateUserVirtualCurrencyRequest
	isSet bool
}

func (v NullableUpdateUserVirtualCurrencyRequest) Get() *UpdateUserVirtualCurrencyRequest {
	return v.value
}

func (v *NullableUpdateUserVirtualCurrencyRequest) Set(val *UpdateUserVirtualCurrencyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateUserVirtualCurrencyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateUserVirtualCurrencyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateUserVirtualCurrencyRequest(val *UpdateUserVirtualCurrencyRequest) *NullableUpdateUserVirtualCurrencyRequest {
	return &NullableUpdateUserVirtualCurrencyRequest{value: val, isSet: true}
}

func (v NullableUpdateUserVirtualCurrencyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateUserVirtualCurrencyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
