/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// AuthAnonLoginResponse struct for AuthAnonLoginResponse
type AuthAnonLoginResponse struct {
	User *AuthUser `json:"user,omitempty"`
}

// NewAuthAnonLoginResponse instantiates a new AuthAnonLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthAnonLoginResponse() *AuthAnonLoginResponse {
	this := AuthAnonLoginResponse{}
	return &this
}

// NewAuthAnonLoginResponseWithDefaults instantiates a new AuthAnonLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthAnonLoginResponseWithDefaults() *AuthAnonLoginResponse {
	this := AuthAnonLoginResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *AuthAnonLoginResponse) GetUser() AuthUser {
	if o == nil || isNil(o.User) {
		var ret AuthUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthAnonLoginResponse) GetUserOk() (*AuthUser, bool) {
	if o == nil || isNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AuthAnonLoginResponse) HasUser() bool {
	if o != nil && !isNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given AuthUser and assigns it to the User field.
func (o *AuthAnonLoginResponse) SetUser(v AuthUser) {
	o.User = &v
}

func (o AuthAnonLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.User) {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableAuthAnonLoginResponse struct {
	value *AuthAnonLoginResponse
	isSet bool
}

func (v NullableAuthAnonLoginResponse) Get() *AuthAnonLoginResponse {
	return v.value
}

func (v *NullableAuthAnonLoginResponse) Set(val *AuthAnonLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthAnonLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthAnonLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthAnonLoginResponse(val *AuthAnonLoginResponse) *NullableAuthAnonLoginResponse {
	return &NullableAuthAnonLoginResponse{value: val, isSet: true}
}

func (v NullableAuthAnonLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthAnonLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
