/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// AuthFacebookLoginResponse struct for AuthFacebookLoginResponse
type AuthFacebookLoginResponse struct {
	User *AuthUser `json:"user,omitempty"`
}

// NewAuthFacebookLoginResponse instantiates a new AuthFacebookLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthFacebookLoginResponse() *AuthFacebookLoginResponse {
	this := AuthFacebookLoginResponse{}
	return &this
}

// NewAuthFacebookLoginResponseWithDefaults instantiates a new AuthFacebookLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthFacebookLoginResponseWithDefaults() *AuthFacebookLoginResponse {
	this := AuthFacebookLoginResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *AuthFacebookLoginResponse) GetUser() AuthUser {
	if o == nil || isNil(o.User) {
		var ret AuthUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthFacebookLoginResponse) GetUserOk() (*AuthUser, bool) {
	if o == nil || isNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AuthFacebookLoginResponse) HasUser() bool {
	if o != nil && !isNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given AuthUser and assigns it to the User field.
func (o *AuthFacebookLoginResponse) SetUser(v AuthUser) {
	o.User = &v
}

func (o AuthFacebookLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.User) {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableAuthFacebookLoginResponse struct {
	value *AuthFacebookLoginResponse
	isSet bool
}

func (v NullableAuthFacebookLoginResponse) Get() *AuthFacebookLoginResponse {
	return v.value
}

func (v *NullableAuthFacebookLoginResponse) Set(val *AuthFacebookLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthFacebookLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthFacebookLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthFacebookLoginResponse(val *AuthFacebookLoginResponse) *NullableAuthFacebookLoginResponse {
	return &NullableAuthFacebookLoginResponse{value: val, isSet: true}
}

func (v NullableAuthFacebookLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthFacebookLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
