/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// RemoteConfigGetUserConfigResponse struct for RemoteConfigGetUserConfigResponse
type RemoteConfigGetUserConfigResponse struct {
	// Config for the user
	Config map[string]interface{} `json:"config,omitempty"`
}

// NewRemoteConfigGetUserConfigResponse instantiates a new RemoteConfigGetUserConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteConfigGetUserConfigResponse() *RemoteConfigGetUserConfigResponse {
	this := RemoteConfigGetUserConfigResponse{}
	return &this
}

// NewRemoteConfigGetUserConfigResponseWithDefaults instantiates a new RemoteConfigGetUserConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteConfigGetUserConfigResponseWithDefaults() *RemoteConfigGetUserConfigResponse {
	this := RemoteConfigGetUserConfigResponse{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *RemoteConfigGetUserConfigResponse) GetConfig() map[string]interface{} {
	if o == nil || isNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteConfigGetUserConfigResponse) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *RemoteConfigGetUserConfigResponse) HasConfig() bool {
	if o != nil && !isNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *RemoteConfigGetUserConfigResponse) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o RemoteConfigGetUserConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableRemoteConfigGetUserConfigResponse struct {
	value *RemoteConfigGetUserConfigResponse
	isSet bool
}

func (v NullableRemoteConfigGetUserConfigResponse) Get() *RemoteConfigGetUserConfigResponse {
	return v.value
}

func (v *NullableRemoteConfigGetUserConfigResponse) Set(val *RemoteConfigGetUserConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteConfigGetUserConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteConfigGetUserConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteConfigGetUserConfigResponse(val *RemoteConfigGetUserConfigResponse) *NullableRemoteConfigGetUserConfigResponse {
	return &NullableRemoteConfigGetUserConfigResponse{value: val, isSet: true}
}

func (v NullableRemoteConfigGetUserConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteConfigGetUserConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
