/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// ProfilesGetProfileResponse struct for ProfilesGetProfileResponse
type ProfilesGetProfileResponse struct {
	// JSON representation of the user's profile visible to the logged in user
	Profile map[string]interface{} `json:"profile,omitempty"`
}

// NewProfilesGetProfileResponse instantiates a new ProfilesGetProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfilesGetProfileResponse() *ProfilesGetProfileResponse {
	this := ProfilesGetProfileResponse{}
	return &this
}

// NewProfilesGetProfileResponseWithDefaults instantiates a new ProfilesGetProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfilesGetProfileResponseWithDefaults() *ProfilesGetProfileResponse {
	this := ProfilesGetProfileResponse{}
	return &this
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *ProfilesGetProfileResponse) GetProfile() map[string]interface{} {
	if o == nil || isNil(o.Profile) {
		var ret map[string]interface{}
		return ret
	}
	return o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfilesGetProfileResponse) GetProfileOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Profile) {
		return map[string]interface{}{}, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *ProfilesGetProfileResponse) HasProfile() bool {
	if o != nil && !isNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given map[string]interface{} and assigns it to the Profile field.
func (o *ProfilesGetProfileResponse) SetProfile(v map[string]interface{}) {
	o.Profile = v
}

func (o ProfilesGetProfileResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	return json.Marshal(toSerialize)
}

type NullableProfilesGetProfileResponse struct {
	value *ProfilesGetProfileResponse
	isSet bool
}

func (v NullableProfilesGetProfileResponse) Get() *ProfilesGetProfileResponse {
	return v.value
}

func (v *NullableProfilesGetProfileResponse) Set(val *ProfilesGetProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProfilesGetProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProfilesGetProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfilesGetProfileResponse(val *ProfilesGetProfileResponse) *NullableProfilesGetProfileResponse {
	return &NullableProfilesGetProfileResponse{value: val, isSet: true}
}

func (v NullableProfilesGetProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfilesGetProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
