/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// MatchmakingCreateTicketResponse struct for MatchmakingCreateTicketResponse
type MatchmakingCreateTicketResponse struct {
	Ticket *MatchmakingTicket `json:"ticket,omitempty"`
}

// NewMatchmakingCreateTicketResponse instantiates a new MatchmakingCreateTicketResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchmakingCreateTicketResponse() *MatchmakingCreateTicketResponse {
	this := MatchmakingCreateTicketResponse{}
	return &this
}

// NewMatchmakingCreateTicketResponseWithDefaults instantiates a new MatchmakingCreateTicketResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchmakingCreateTicketResponseWithDefaults() *MatchmakingCreateTicketResponse {
	this := MatchmakingCreateTicketResponse{}
	return &this
}

// GetTicket returns the Ticket field value if set, zero value otherwise.
func (o *MatchmakingCreateTicketResponse) GetTicket() MatchmakingTicket {
	if o == nil || isNil(o.Ticket) {
		var ret MatchmakingTicket
		return ret
	}
	return *o.Ticket
}

// GetTicketOk returns a tuple with the Ticket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatchmakingCreateTicketResponse) GetTicketOk() (*MatchmakingTicket, bool) {
	if o == nil || isNil(o.Ticket) {
		return nil, false
	}
	return o.Ticket, true
}

// HasTicket returns a boolean if a field has been set.
func (o *MatchmakingCreateTicketResponse) HasTicket() bool {
	if o != nil && !isNil(o.Ticket) {
		return true
	}

	return false
}

// SetTicket gets a reference to the given MatchmakingTicket and assigns it to the Ticket field.
func (o *MatchmakingCreateTicketResponse) SetTicket(v MatchmakingTicket) {
	o.Ticket = &v
}

func (o MatchmakingCreateTicketResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Ticket) {
		toSerialize["ticket"] = o.Ticket
	}
	return json.Marshal(toSerialize)
}

type NullableMatchmakingCreateTicketResponse struct {
	value *MatchmakingCreateTicketResponse
	isSet bool
}

func (v NullableMatchmakingCreateTicketResponse) Get() *MatchmakingCreateTicketResponse {
	return v.value
}

func (v *NullableMatchmakingCreateTicketResponse) Set(val *MatchmakingCreateTicketResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchmakingCreateTicketResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchmakingCreateTicketResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchmakingCreateTicketResponse(val *MatchmakingCreateTicketResponse) *NullableMatchmakingCreateTicketResponse {
	return &NullableMatchmakingCreateTicketResponse{value: val, isSet: true}
}

func (v NullableMatchmakingCreateTicketResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchmakingCreateTicketResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
