/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// BatchUpdateUserStatisticsRequest struct for BatchUpdateUserStatisticsRequest
type BatchUpdateUserStatisticsRequest struct {
	// Array of operations to be performed
	Data []StatisticsBatchUpdateUserStatisticsItem `json:"data"`
}

// NewBatchUpdateUserStatisticsRequest instantiates a new BatchUpdateUserStatisticsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchUpdateUserStatisticsRequest(data []StatisticsBatchUpdateUserStatisticsItem) *BatchUpdateUserStatisticsRequest {
	this := BatchUpdateUserStatisticsRequest{}
	this.Data = data
	return &this
}

// NewBatchUpdateUserStatisticsRequestWithDefaults instantiates a new BatchUpdateUserStatisticsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchUpdateUserStatisticsRequestWithDefaults() *BatchUpdateUserStatisticsRequest {
	this := BatchUpdateUserStatisticsRequest{}
	return &this
}

// GetData returns the Data field value
func (o *BatchUpdateUserStatisticsRequest) GetData() []StatisticsBatchUpdateUserStatisticsItem {
	if o == nil {
		var ret []StatisticsBatchUpdateUserStatisticsItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BatchUpdateUserStatisticsRequest) GetDataOk() ([]StatisticsBatchUpdateUserStatisticsItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BatchUpdateUserStatisticsRequest) SetData(v []StatisticsBatchUpdateUserStatisticsItem) {
	o.Data = v
}

func (o BatchUpdateUserStatisticsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableBatchUpdateUserStatisticsRequest struct {
	value *BatchUpdateUserStatisticsRequest
	isSet bool
}

func (v NullableBatchUpdateUserStatisticsRequest) Get() *BatchUpdateUserStatisticsRequest {
	return v.value
}

func (v *NullableBatchUpdateUserStatisticsRequest) Set(val *BatchUpdateUserStatisticsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchUpdateUserStatisticsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchUpdateUserStatisticsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchUpdateUserStatisticsRequest(val *BatchUpdateUserStatisticsRequest) *NullableBatchUpdateUserStatisticsRequest {
	return &NullableBatchUpdateUserStatisticsRequest{value: val, isSet: true}
}

func (v NullableBatchUpdateUserStatisticsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchUpdateUserStatisticsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
