/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// AuthAppleLoginResponse struct for AuthAppleLoginResponse
type AuthAppleLoginResponse struct {
	User *AuthUser `json:"user,omitempty"`
}

// NewAuthAppleLoginResponse instantiates a new AuthAppleLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthAppleLoginResponse() *AuthAppleLoginResponse {
	this := AuthAppleLoginResponse{}
	return &this
}

// NewAuthAppleLoginResponseWithDefaults instantiates a new AuthAppleLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthAppleLoginResponseWithDefaults() *AuthAppleLoginResponse {
	this := AuthAppleLoginResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *AuthAppleLoginResponse) GetUser() AuthUser {
	if o == nil || isNil(o.User) {
		var ret AuthUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthAppleLoginResponse) GetUserOk() (*AuthUser, bool) {
	if o == nil || isNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AuthAppleLoginResponse) HasUser() bool {
	if o != nil && !isNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given AuthUser and assigns it to the User field.
func (o *AuthAppleLoginResponse) SetUser(v AuthUser) {
	o.User = &v
}

func (o AuthAppleLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.User) {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableAuthAppleLoginResponse struct {
	value *AuthAppleLoginResponse
	isSet bool
}

func (v NullableAuthAppleLoginResponse) Get() *AuthAppleLoginResponse {
	return v.value
}

func (v *NullableAuthAppleLoginResponse) Set(val *AuthAppleLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthAppleLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthAppleLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthAppleLoginResponse(val *AuthAppleLoginResponse) *NullableAuthAppleLoginResponse {
	return &NullableAuthAppleLoginResponse{value: val, isSet: true}
}

func (v NullableAuthAppleLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthAppleLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
