/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// MatchmakingDeleteTicketResponse struct for MatchmakingDeleteTicketResponse
type MatchmakingDeleteTicketResponse struct {
	Success *bool `json:"success,omitempty"`
}

// NewMatchmakingDeleteTicketResponse instantiates a new MatchmakingDeleteTicketResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchmakingDeleteTicketResponse() *MatchmakingDeleteTicketResponse {
	this := MatchmakingDeleteTicketResponse{}
	return &this
}

// NewMatchmakingDeleteTicketResponseWithDefaults instantiates a new MatchmakingDeleteTicketResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchmakingDeleteTicketResponseWithDefaults() *MatchmakingDeleteTicketResponse {
	this := MatchmakingDeleteTicketResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *MatchmakingDeleteTicketResponse) GetSuccess() bool {
	if o == nil || isNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MatchmakingDeleteTicketResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || isNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *MatchmakingDeleteTicketResponse) HasSuccess() bool {
	if o != nil && !isNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *MatchmakingDeleteTicketResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o MatchmakingDeleteTicketResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableMatchmakingDeleteTicketResponse struct {
	value *MatchmakingDeleteTicketResponse
	isSet bool
}

func (v NullableMatchmakingDeleteTicketResponse) Get() *MatchmakingDeleteTicketResponse {
	return v.value
}

func (v *NullableMatchmakingDeleteTicketResponse) Set(val *MatchmakingDeleteTicketResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchmakingDeleteTicketResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchmakingDeleteTicketResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchmakingDeleteTicketResponse(val *MatchmakingDeleteTicketResponse) *NullableMatchmakingDeleteTicketResponse {
	return &NullableMatchmakingDeleteTicketResponse{value: val, isSet: true}
}

func (v NullableMatchmakingDeleteTicketResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchmakingDeleteTicketResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
