/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// StorageUpdateAppendBlobResponse struct for StorageUpdateAppendBlobResponse
type StorageUpdateAppendBlobResponse struct {
	// CAS value used for future operations
	Cas *string `json:"cas,omitempty"`
}

// NewStorageUpdateAppendBlobResponse instantiates a new StorageUpdateAppendBlobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageUpdateAppendBlobResponse() *StorageUpdateAppendBlobResponse {
	this := StorageUpdateAppendBlobResponse{}
	return &this
}

// NewStorageUpdateAppendBlobResponseWithDefaults instantiates a new StorageUpdateAppendBlobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageUpdateAppendBlobResponseWithDefaults() *StorageUpdateAppendBlobResponse {
	this := StorageUpdateAppendBlobResponse{}
	return &this
}

// GetCas returns the Cas field value if set, zero value otherwise.
func (o *StorageUpdateAppendBlobResponse) GetCas() string {
	if o == nil || isNil(o.Cas) {
		var ret string
		return ret
	}
	return *o.Cas
}

// GetCasOk returns a tuple with the Cas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageUpdateAppendBlobResponse) GetCasOk() (*string, bool) {
	if o == nil || isNil(o.Cas) {
		return nil, false
	}
	return o.Cas, true
}

// HasCas returns a boolean if a field has been set.
func (o *StorageUpdateAppendBlobResponse) HasCas() bool {
	if o != nil && !isNil(o.Cas) {
		return true
	}

	return false
}

// SetCas gets a reference to the given string and assigns it to the Cas field.
func (o *StorageUpdateAppendBlobResponse) SetCas(v string) {
	o.Cas = &v
}

func (o StorageUpdateAppendBlobResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Cas) {
		toSerialize["cas"] = o.Cas
	}
	return json.Marshal(toSerialize)
}

type NullableStorageUpdateAppendBlobResponse struct {
	value *StorageUpdateAppendBlobResponse
	isSet bool
}

func (v NullableStorageUpdateAppendBlobResponse) Get() *StorageUpdateAppendBlobResponse {
	return v.value
}

func (v *NullableStorageUpdateAppendBlobResponse) Set(val *StorageUpdateAppendBlobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageUpdateAppendBlobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageUpdateAppendBlobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageUpdateAppendBlobResponse(val *StorageUpdateAppendBlobResponse) *NullableStorageUpdateAppendBlobResponse {
	return &NullableStorageUpdateAppendBlobResponse{value: val, isSet: true}
}

func (v NullableStorageUpdateAppendBlobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageUpdateAppendBlobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
