/*
Roi_dev

Your custom SDK

API version: Roi_dev: v9 SDK
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package snapser

import (
	"encoding/json"
)

// IncrementScoreRequest struct for IncrementScoreRequest
type IncrementScoreRequest struct {
	// The delta of the score to increment
	Delta float64 `json:"delta"`
	// Name of the tier
	TierName *string `json:"tier_name,omitempty"`
}

// NewIncrementScoreRequest instantiates a new IncrementScoreRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncrementScoreRequest(delta float64) *IncrementScoreRequest {
	this := IncrementScoreRequest{}
	this.Delta = delta
	return &this
}

// NewIncrementScoreRequestWithDefaults instantiates a new IncrementScoreRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncrementScoreRequestWithDefaults() *IncrementScoreRequest {
	this := IncrementScoreRequest{}
	return &this
}

// GetDelta returns the Delta field value
func (o *IncrementScoreRequest) GetDelta() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value
// and a boolean to check if the value has been set.
func (o *IncrementScoreRequest) GetDeltaOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delta, true
}

// SetDelta sets field value
func (o *IncrementScoreRequest) SetDelta(v float64) {
	o.Delta = v
}

// GetTierName returns the TierName field value if set, zero value otherwise.
func (o *IncrementScoreRequest) GetTierName() string {
	if o == nil || isNil(o.TierName) {
		var ret string
		return ret
	}
	return *o.TierName
}

// GetTierNameOk returns a tuple with the TierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncrementScoreRequest) GetTierNameOk() (*string, bool) {
	if o == nil || isNil(o.TierName) {
		return nil, false
	}
	return o.TierName, true
}

// HasTierName returns a boolean if a field has been set.
func (o *IncrementScoreRequest) HasTierName() bool {
	if o != nil && !isNil(o.TierName) {
		return true
	}

	return false
}

// SetTierName gets a reference to the given string and assigns it to the TierName field.
func (o *IncrementScoreRequest) SetTierName(v string) {
	o.TierName = &v
}

func (o IncrementScoreRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["delta"] = o.Delta
	}
	if !isNil(o.TierName) {
		toSerialize["tier_name"] = o.TierName
	}
	return json.Marshal(toSerialize)
}

type NullableIncrementScoreRequest struct {
	value *IncrementScoreRequest
	isSet bool
}

func (v NullableIncrementScoreRequest) Get() *IncrementScoreRequest {
	return v.value
}

func (v *NullableIncrementScoreRequest) Set(val *IncrementScoreRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIncrementScoreRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIncrementScoreRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncrementScoreRequest(val *IncrementScoreRequest) *NullableIncrementScoreRequest {
	return &NullableIncrementScoreRequest{value: val, isSet: true}
}

func (v NullableIncrementScoreRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncrementScoreRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
