basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Skybull snapser cloud code
  title: Skybull Snapser CloudeCode
  version: 0.0.1
paths:
  /v1/byosnap-skybull-cloudcode/buy-energy:
    get:
      consumes:
      - multipart/form-data
      description: Get energy
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: query
        name: userId
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get energy
    post:
      consumes:
      - multipart/form-data
      description: Buy energy by gold
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Buy energy by gold
  /v1/byosnap-skybull-cloudcode/create-campaign-game:
    post:
      consumes:
      - multipart/form-data
      description: Create campaign game and subject energy
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Call when start a campaign game
  /v1/byosnap-skybull-cloudcode/create-pvp-game:
    post:
      consumes:
      - multipart/form-data
      description: Level up equipment
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: id of the pvp game
        in: formData
        name: matchId
        required: true
        type: string
      - description: id of opponent
        in: formData
        name: opponentID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Level up equipment
  /v1/byosnap-skybull-cloudcode/level-up-champion:
    post:
      consumes:
      - multipart/form-data
      description: Level up champion
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: champion userID
        in: formData
        name: userChampionUid
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Level up champion
  /v1/byosnap-skybull-cloudcode/level-up-equipment:
    post:
      consumes:
      - multipart/form-data
      description: Level up equipment
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: id of equipment player want to level up
        in: formData
        name: userEquipmentUID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Level up equipment
  /v1/byosnap-skybull-cloudcode/re-roll-equipment-modifier:
    post:
      consumes:
      - multipart/form-data
      description: Re-roll player equipment modifier
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: id of equipment player want to re-roll
        in: formData
        name: UserEquipmentUID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Re-Roll equipment modifier
  /v1/byosnap-skybull-cloudcode/sell-equipment:
    post:
      consumes:
      - multipart/form-data
      description: Sell player equipment
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: id of equipment player want to sell
        in: formData
        name: UserEquipmentUID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sell equipment
  /v1/byosnap-skybull-cloudcode/win-campaign:
    post:
      consumes:
      - multipart/form-data
      description: Call when win a campaign
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login with snapser
        in: formData
        name: userId
        required: true
        type: string
      - description: session token for login version
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: power stage player win
        in: formData
        name: stagePower
        required: true
        type: string
      - description: the start they reach
        in: formData
        name: star
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Call when win a campaign
  /v1/byosnap-skybull-cloudcode/win-pvp:
    post:
      consumes:
      - multipart/form-data
      description: Call when player win a pvp game
      parameters:
      - description: Authorization Token
        format: uuid
        in: header
        name: token
        required: true
        type: string
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: 'opponent snapser id '
        in: formData
        name: opponentID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Call when player win a pvp game
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
