basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Skybull snapser cloud code
  title: Skybull Snapser CloudeCode
  version: 0.0.1
paths:
  /v2/byosnap-skybull/level-up-champion:
    post:
      consumes:
      - multipart/form-data
      description: Level up champion
      parameters:
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: champion userID
        in: formData
        name: championUserId
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Level up champion
  /v2/byosnap-skybull/level-up-equipment:
    post:
      consumes:
      - multipart/form-data
      description: Level up equipment
      parameters:
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: id of equipment player want to level up
        in: formData
        name: UserEquipmentUID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Level up equipment
  /v2/byosnap-skybull/re-roll-equipment-modifier:
    post:
      consumes:
      - multipart/form-data
      description: Re-roll player equipment modifier
      parameters:
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: id of equipment player want to re-roll
        in: formData
        name: UserEquipmentUID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Re-Roll equipment modifier
  /v2/byosnap-skybull/sell-equipment:
    post:
      consumes:
      - multipart/form-data
      description: Sell player equipment
      parameters:
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: id of equipment player want to sell
        in: formData
        name: UserEquipmentUID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sell equipment
  /v2/byosnap-skybull/win-campaign:
    post:
      consumes:
      - multipart/form-data
      description: Call when win a campaign
      parameters:
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: power stage player win
        in: formData
        name: stagePower
        required: true
        type: string
      - description: the start they reach
        in: formData
        name: star
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Call when win a campaign
  /v2/byosnap-skybull/win-pvp:
    post:
      consumes:
      - multipart/form-data
      description: Call when player win a pvp game
      parameters:
      - description: userId when they login
        in: formData
        name: userId
        required: true
        type: string
      - description: session token
        in: formData
        name: sessionToken
        required: true
        type: string
      - description: 'opponent snapser id '
        in: formData
        name: opponentID
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Call when player win a pvp game
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
